kakaotrack/opensource-class

github/chappi12.txt

add chappi12

---

github-2016/iolo.md

add iolo's resume

---

github-2016/resume.md

15학번 양소희 자기소개서 제출합니다.

---

github-2016/2015108175.md

2015108175 강다희 자기소개서 제출입니다.

---

github-2016/jinhyeok.md

2010108174 강진혁

---

github-2016/2010108177.md

2010108177 김경호 자소서입니다

---

github-2016/2010108021 컴퓨터공학과 이영재.md

github-2016/2010108021 컴퓨터공학과 이영재.md

---

github-2016/2015108175.md

2015108175 강다희 중간고사 과제 제출입니다.

---

github-2016/2010108021 컴퓨터공학과 이영재.md

2010108201 컴퓨터공학과 이영재 자기소개서 중간고사대체 

---

github-2016/2010108174_강진혁.md

Fork한 내용을 추가했습니다.
자기소개내용은 추가할점이 따로 없어서 회사명만 수정했습니다. (Kakao Corp -> Kakao)

2010108174 강진혁 중간과제 제출합니다 :)

---

github-2016/2010108177.md

2010108177-김경호 중간고사대체

---

github-2016/2016108196양소희.md

2016108196양소희 중간과제 제출합니다.

---

github-2017/2011108211.md

2011108211 홍진범 자기소개서 추가

---

github-2017/2016104135.md

컴퓨터교육과 2016104135 김유리 자기소개서 제출합니다.

컴퓨터교육과 김유리 자기소개서

---

github-2017/2016104135.md

컴퓨터교육과 김유리 자기소개서 이미지 수정

---

github-2018/2015108189.md

컴퓨터공학과 김한주 자기소개서 2015108189.md

---

github-2018/2017108249.md

2017108249 고혜림 자기소개서

---

github-2018/2017108244 강수연.md

2017108244

---

github-2018/2015108180_김기현_수정.md

2015108180 김기현 자기소개서입니다.

---

github-2018/2015108176.md

2015108176 강용재 자기소개 업데이트

---

github-2018/2017108249.md

fork 부분 수정하였고 홈페이지를 작성하여 자기소개 md파일에 링크 첨부하였습니다.

2017108249 고혜림 중간고사 대체 과제 제출

---

github-2020/2015104138.md

컴퓨터교육과 2015104138 김장혁입니다.
자기소개서를 깃허브 페이지에 작성하였습니다.

자기소개서 Update

---

github-2020/2019208021.md

2019208021

---

github-2020/2016108281_임명철.md

자기소개서 제출
https://immyeong.github.io

2016108281_임명철

---

2019208013 김규리.md

2019208013 김규리<br>
자기소개서 과제 제출<br>
url : -<a href="http://asdf130700.github.io">http://asdf130700.github.io</a>

2019208013 김규리

---

github-2020/2016108260_김영일

자기소개서+ 포크 과제 제출
link : http://zeronek.github.io

2016108260_김영일

---

2019208017 김현규.md

자기소개서 만들기
https://khk283855.github.io/
[2019208017 김현규.txt](https://github.com/kakaotrack/opensource-class/files/4769628/2019208017.txt)

2019208017 김현규

---

github-2021/2017104124 김선규.md

2017104124 김선규 자기소개서 추가

---

github-2021/2019104127.md

김유진 자기소개서 추가

---

github-2021/2019108276_최윤서.md

2019108276_최윤서

---

github-2021/2019104124.md

2019104124 고은빈 자기소개 재업로드

---

github-2021/2019108268.md

Update 2019108268 옥해은 중간과제

---

github-2021/2019108250.md

김나연 2019108250.md

---

github-2021/2017108252.md

2017108252 권영기 중간고사 과제

---

github-2021/2017108275.md

Update 홍기준 2017108275.md

---

github-2021/2019104124.md

2019104124 고은빈 자기소개 page 추가했습니다.

2019104124 고은빈 자기소개 page 추가

---

github-2021/2016108271-양상우.md

1. 깃허브 페이지 URL을 등록했습니다 (아이디가 두개라, URL이 다릅니다)
2. 깃허브 페이지에 카테고리를 추가했습니다. (포커스 -> 상단 노출)
감사합니다.

2016108271 양상우 중간고사과제 제출입니다.

---

github-2021/2014108196-양지웅.md

update blog 양지웅 2014108196

---

github-2021/2017108243-강성범-중간고사.md

2017108243 강성범 중간고사

---

github-2021/2019104127.md

중간대체과제입니다-김유진

---

github-2021/2017108262-김희범.md

2017108262 김희범 자기소개 블로그입니다.

---

github-2022/README.md

Create github-2022 README.md

---

github-2022/2018108253-김찬우.md
github-2022/README.md

2018108253 김찬우

---

github-2022/2019105041-정혜연.md

2019105041-정혜연

---

github-2022/2020104125-김다현.md

김다현 자기소개서 추가

---

github-2022/2020108257-박영준.md

박영준 자기소개서 추가

---

github-2022/2018104135-현수빈.md

fork 부분에 제 저장소에 fork한 링크 추가하여 pr 다시 보냅니다!

현수빈 자기소개서 수정

---

github-2022/2015101268_김나영.md

김나영_중간과제: 자기소개서 페이지 추가

---

github-2022/2015107187양강호.md

2015107187 양강호 중간고사 과제 제출

---

github-2022/2019104128_김윤태.md

2019104128 김윤태 자기소개서 최종입니다.
원래 사용하던 깃허브 계정을 삭제하고 새로 만들어서 전에 올렸던 자기소개서가 사라져 다시 업로드합니다!

2019104128 김윤태 중간고사 제출

---

github-2022/2018104135-현수빈.md

2018104135-현수빈.md 파일에 github pages 링크를 추가했습니다.
추가된 링크 
https://subinhyun.github.io/
https://subinhyun.github.io/blog/

2018104135 현수빈 중간고사 과제 제출

---

github-2023/2020102127-김다희.md

원래 github블로그가 있어서 자기소개서와 함께 테마를 커스텀한 내용도 추가했습니다.

김다희 자기소개서 추가

---

github-2023/2020104139-최종민.md

Update 2023.04.23 자기소개서 Upload

최종민 자기소개서 추가

---

github-2023/2021108030-권혁원.md

Github Pages로 제작한 Portfolio링크 추가합니다.

권혁원 git portfolio추가

---

github-2023/2023208015-윤혁준.md

2023208015 윤혁준 중간고사 과제 제출
